schema:
  - lib/**/*.graphql
  - ${NEXT_PUBLIC_GRAPHQL_URI}:
      headers:
        authorization: ${TOKEN}
documents:
  - lib/**/*.gql
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: .cache
